#!/bin/sh -eu

LOG_LEVEL=2
LOG_DATEFORMAT='+%Y-%m-%d %H:%M:%S'

log_debug() {
	[ "$LOG_LEVEL" -le 1 ] && _log DEBUG "$1"
}

log_info() {
	[ "$LOG_LEVEL" -le 2 ] && _log INFO "$1"
}

log_warning() {
	[ "$LOG_LEVEL" -le 3 ] && _log WARNING "$1"
}

log_error() {
	[ "$LOG_LEVEL" -le 4 ] && _log ERROR "$1"
}

_log() {
	level="$1"
	msg="$2"
	printf '[%s] [%s] %s\n' "$(date "$LOG_DATEFORMAT")" "$level" "$msg"
}
